namespace Strunika.Neural;

/// <summary>
/// Constant-Q transform matching the BTC training front-end (librosa.cqt):
/// 144 bins, 24 per octave from C1, hop 2048 at 22050 Hz, Hann kernels,
/// log(|CQT| + 1e-6) output, audio processed in 10-second chunks exactly
/// like BTC's audio_file_to_features (chunk edges included).
///
/// Implementation is the DIRECT transform (per-frame kernel correlation),
/// not librosa's recursive downsampling — validated against golden files
/// generated by the Python reference pipeline.
/// </summary>
public sealed class CqtExtractor
{
    public const int SampleRate = 22050;
    public const int Bins = 144;
    public const int BinsPerOctave = 24;
    public const int Hop = 2048;
    public const double FMin = 32.70319566257483; // C1
    public const double ChunkSeconds = 10.0;
    public const int FramesPerChunk = 108;

    /// <summary>Global gain matching librosa's normalization convention,
    /// calibrated against golden reference features (log offset 3.850).
    /// Without it quiet bins saturate at the log floor and real-world
    /// (quiet) recordings turn to mush.</summary>
    public const double LibrosaGain = 46.99;

    private readonly float[][] _kernelsRe;
    private readonly float[][] _kernelsIm;
    private readonly int[] _lengths;

    public CqtExtractor()
    {
        double q = 1.0 / (Math.Pow(2.0, 1.0 / BinsPerOctave) - 1.0);
        _kernelsRe = new float[Bins][];
        _kernelsIm = new float[Bins][];
        _lengths = new int[Bins];

        for (int k = 0; k < Bins; k++)
        {
            double freq = FMin * Math.Pow(2.0, k / (double)BinsPerOctave);
            int length = (int)Math.Ceiling(q * SampleRate / freq);
            _lengths[k] = length;

            var re = new float[length];
            var im = new float[length];
            double norm = 0;
            for (int n = 0; n < length; n++)
            {
                // Hann window over the kernel span.
                double w = 0.5 * (1 - Math.Cos(2 * Math.PI * n / length));
                norm += w;
            }
            for (int n = 0; n < length; n++)
            {
                double w = 0.5 * (1 - Math.Cos(2 * Math.PI * n / length));
                // Centered complex exponential, L1-normalized like librosa.
                double phase = -2.0 * Math.PI * freq * (n - length / 2.0) / SampleRate;
                re[n] = (float)(w * Math.Cos(phase) / norm);
                im[n] = (float)(w * Math.Sin(phase) / norm);
            }
            _kernelsRe[k] = re;
            _kernelsIm[k] = im;
        }
    }

    public double SecondsPerFrame => ChunkSeconds / FramesPerChunk;

    /// <summary>log-CQT features [frames, 144] for 22050 Hz mono audio.</summary>
    public float[][] Extract(float[] samples, IProgress<double>? progress = null, CancellationToken ct = default)
    {
        int chunkSamples = (int)(SampleRate * ChunkSeconds);
        var features = new List<float[]>();

        int position = 0;
        while (samples.Length > position + chunkSamples)
        {
            ct.ThrowIfCancellationRequested();
            progress?.Report(position / (double)samples.Length);
            AppendChunk(samples, position, chunkSamples, features);
            position += chunkSamples;
        }
        AppendChunk(samples, position, samples.Length - position, features);
        return features.ToArray();
    }

    /// <summary>Half-length of the longest (lowest-frequency) kernel — how
    /// much context a frame needs on each side of its center.</summary>
    public int MaxKernelHalf => _lengths[0] / 2 + 1;

    /// <summary>
    /// One CQT frame centered at <paramref name="center"/>, kernels clipped
    /// to the span. Used by the live sliding-window path (no 10-second
    /// chunk semantics — a live stream has no chunk boundaries).
    /// </summary>
    public void ComputeFrame(ReadOnlySpan<float> samples, int center, float[] dest)
    {
        for (int k = 0; k < Bins; k++)
        {
            var re = _kernelsRe[k];
            var im = _kernelsIm[k];
            int kernelLength = _lengths[k];
            int start = center - kernelLength / 2;

            int lo = Math.Max(start, 0);
            int hi = Math.Min(start + kernelLength, samples.Length);

            double sumRe = 0, sumIm = 0;
            for (int i = lo; i < hi; i++)
            {
                float s = samples[i];
                int n = i - start;
                sumRe += s * re[n];
                sumIm += s * im[n];
            }
            double magnitude = LibrosaGain * Math.Sqrt(sumRe * sumRe + sumIm * sumIm);
            dest[k] = (float)Math.Log(magnitude + 1e-6);
        }
    }

    private void AppendChunk(float[] samples, int offset, int length, List<float[]> features)
    {
        // librosa: frames = 1 + length // hop, frame m centered at m * hop,
        // zeros beyond the chunk (each chunk is transformed independently).
        int frames = 1 + length / Hop;
        for (int m = 0; m < frames && features.Count < 1_000_000; m++)
        {
            var row = new float[Bins];
            int center = offset + m * Hop;
            for (int k = 0; k < Bins; k++)
            {
                var re = _kernelsRe[k];
                var im = _kernelsIm[k];
                int kernelLength = _lengths[k];
                int start = center - kernelLength / 2;

                // Clip the kernel to both the chunk and the signal.
                int lo = Math.Max(start, offset);
                int hi = Math.Min(start + kernelLength, Math.Min(offset + length, samples.Length));

                double sumRe = 0, sumIm = 0;
                for (int i = lo; i < hi; i++)
                {
                    float s = samples[i];
                    int n = i - start;
                    sumRe += s * re[n];
                    sumIm += s * im[n];
                }
                double magnitude = LibrosaGain * Math.Sqrt(sumRe * sumRe + sumIm * sumIm);
                row[k] = (float)Math.Log(magnitude + 1e-6);
            }
            features.Add(row);
        }
    }
}
