<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Strunika.Neural</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strunika.Core\Strunika.Core.csproj" />
  </ItemGroup>

</Project>
